import "./globals.css";

export const metadata = {
  title: "Sistema de Controle de Endereçamento",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
